@startuml
Customer -> TPP: PSU requests debit card access at TPP
TPP -> Xs2a: [POST] register debit card access access consent requests
note right: validate \n 1. eIDAS certificate \n 2. request syntax \n 3. TPP role \n 4. Semantics

@enduml